Repository kanderson852/viewing_party_lite, pull requests merged in 2022-02, with the labels that each got.

#13 Resolves #12
  docs/pr_template.md
Labels: documentation

#14 Gemfile additions
  .gitignore
  Gemfile
  Gemfile.lock
  spec/factories/.keep
  spec/rails_helper.rb
  spec/support/factory_bot.rb
Labels: enhancement

#16 Factory bot setup and Rubocop formatting
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/guest_party.rb
  app/models/party.rb
  app/models/user.rb
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/content_security_policy.rb
  config/initializers/cookies_serializer.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/mime_types.rb
  config/initializers/wrap_parameters.rb
  config/puma.rb
  config/routes.rb
  db/migrate/20220201042500_create_users.rb
  db/migrate/20220201043506_create_parties.rb
  db/migrate/20220201043615_create_guest_parties.rb
  db/seeds.rb
  spec/factories/.keep
  spec/factories/guest_parties.rb
  spec/factories/parties.rb
  spec/factories/users.rb
  spec/models/guest_party_spec.rb
  spec/models/party_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
Labels: enhancement

#19 Valid email validation
  Gemfile
  Gemfile.lock
  app/models/user.rb
  db/migrate/20220201042500_create_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: enhancement

#20 Resolves #8
  app/controllers/users_controller.rb
  app/views/users/new.html.erb
  spec/features/users/new_spec.rb
Labels: enhancement

#21 User Dashboard page
  app/views/users/show.html.erb
  spec/features/users/show_spec.rb
Labels: enhancement

#22 Party
  app/controllers/parties_controller.rb
  app/controllers/user_parties_controller.rb
  app/controllers/users_controller.rb
  app/models/party.rb
  app/models/user.rb
  app/models/user_party.rb
  app/views/parties/new.html.erb
  config/routes.rb
  db/migrate/20220202181400_create_user_parties.rb
  db/schema.rb
  spec/factories/user_parties.rb
  spec/features/parties/new_spec.rb
  spec/features/users/new_spec.rb
  spec/models/party_spec.rb
  spec/models/user_party_spec.rb
  spec/models/user_spec.rb
Labels: enhancement

#23 Issue #5, Issue #6
  Gemfile
  Gemfile.lock
  app/controllers/movies_controller.rb
  app/controllers/user_movies_controller.rb
  app/controllers/users_controller.rb
  app/views/user_movies/index.html.erb
  app/views/user_movies/show.html.erb
  app/views/users/discover.html.erb
  config/routes.rb
  spec/features/users/discover_spec.rb
Labels: enhancement

#24 Heroku fixes
  Gemfile
  Gemfile.lock
  app/models/user.rb
Labels: bug

#25 Poro creation
  .gitignore
  Gemfile
  app/models/user.rb
  app/poros/cast.rb
  app/poros/movie.rb
  app/poros/review.rb
  spec/poros/cast_spec.rb
  spec/poros/movie_spec.rb
  spec/poros/review_spec.rb
Labels: enhancement

#26 Service and facade setup
  Gemfile
  Gemfile.lock
  app/facades/movies_facade.rb
  app/poros/movie.rb
  app/services/cast_service.rb
  app/services/movie_service.rb
  app/services/review_service.rb
  spec/fixtures/vcr_cassettes/movie_reviews.yml
  spec/fixtures/vcr_cassettes/movie_reviews_2022.yml
  spec/fixtures/vcr_cassettes/movie_reviews_2022_02.yml
  spec/fixtures/vcr_cassettes/movie_reviews_2022_02_02.yml
  spec/poros/movie_spec.rb
  spec/rails_helper.rb
  spec/services/review_service_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#27 Facade exploration
  app/facades/movies_facade.rb
  app/services/review_service.rb
  spec/facades/movies_facade_spec.rb
  spec/fixtures/vcr_cassettes/MoviesFacade/class_methods/_movie_reviews/should_return_array_of_review_objects.yml
  spec/fixtures/vcr_cassettes/ReviewService/class_methods/_conn/returns_reviews.yml
  spec/fixtures/vcr_cassettes/ReviewService/class_methods/_get_reviews/returns_hash_reviews.yml
  spec/fixtures/vcr_cassettes/ReviewService/class_methods/_get_reviews/returns_json_reviews.yml
  spec/fixtures/vcr_cassettes/movie_reviews_2022.yml
  spec/rails_helper.rb
  spec/services/review_service_spec.rb
Labels: enhancement

#28 Set up API consumption for Cast, add it to the Movies facade
  app/facades/movies_facade.rb
  app/services/cast_service.rb
  spec/facades/movies_facade_spec.rb
  spec/factories/cast.rb
  spec/factories/movies.rb
  spec/factories/review.rb
  spec/fixtures/vcr_cassettes/CastService/class_methods/_conn/returns_casts.yml
  spec/fixtures/vcr_cassettes/MoviesFacade/class_methods/_movie_casts/should_return_an_array_of_objects_even_if_cast_is_less_than_10.yml
  spec/fixtures/vcr_cassettes/MoviesFacade/class_methods/_movie_casts/should_return_array_of_cast_objects.yml
  spec/fixtures/vcr_cassettes/movie_casts.yml
  spec/models/cast_spec.rb
  spec/models/movie_spec.rb
  spec/models/review_spec.rb
  spec/services/cast_service_spec.rb
Labels: enhancement

#29 Movie service and facade
  app/facades/movie_facade.rb
  app/facades/movies_facade.rb
  app/poros/movie.rb
  app/services/cast_service.rb
  app/services/movie_service.rb
  app/services/review_service.rb
  spec/facades/movie_facade_spec.rb
  spec/facades/movies_facade_spec.rb
  spec/fixtures/top_rated_movies.json
  spec/fixtures/vcr_cassettes/CastService/class_methods/_get_cast/returns_cast_data.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_create_movie/should_return_movie_objects_with_reviews_and_cast.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_movie_casts/should_return_an_array_of_objects_even_if_cast_is_less_than_10.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_movie_casts/should_return_array_of_cast_objects.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_movie_reviews/should_return_array_of_review_objects.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_top_20_movie_list/should_return_array_movie_objects.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_movie/returns_hash_of_movie_details.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_top_rated_movies/returns_hash_of_top_movies.yml
  spec/fixtures/vcr_cassettes/ReviewService/class_methods/_get_reviews/returns_hash_of_reviews.yml
  spec/poros/movie_spec.rb
  spec/services/cast_service_spec.rb
  spec/services/movie_service_spec.rb
  spec/services/review_service_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#30 Movie search
  app/facades/movie_facade.rb
  app/poros/movie.rb
  app/services/movie_service.rb
  spec/facades/movie_facade_spec.rb
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_search_movie_list/should_return_40_movies_if_able.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_search_movie_list/should_return_an_array_of_queried_movie_objects.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_search_movie_list/should_return_less_than_40_movies_if_there_are_less.yml
  spec/fixtures/vcr_cassettes/MovieFacade/class_methods/_search_movie_list/should_return_no_movies_if_there_are_no_matching.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_get_movie/returns_hash_of_movie_details.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_search_movies/returns_a_blank_array_if_no_movies_found.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_search_movies/returns_array_of_less_than_40_movies_if_less_are_found.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_search_movies/returns_array_of_max_40_movies_if_more_than_40_matches.yml
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_search_movies/returns_array_of_movies_searched_by_query.yml
  spec/services/movie_service_spec.rb
Labels: enhancement

#33 Resolves #4
  app/controllers/user_movies_controller.rb
  app/facades/movie_facade.rb
  app/views/user_movies/index.html.erb
  app/views/user_movies/show.html.erb
  spec/features/user_movies/index_spec.rb
  spec/features/user_movies/show_spec.rb
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/clickable_elements/each_movie_has_links_redirecting_to_view_the_movie_details.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/clickable_elements/has_movie_links_to_view_the_movie_details.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/clickable_elements/returns_back_to_the_discover_page_when_clicked.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_20_names_and_average_of_the_top_rated_movies.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_20_names_in_the_top_rated_movies.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_40_names_and_averages_if_there_are_over_40_movie_matches.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_a_button_to_return_to_discover_page_when_on_top_rated.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_a_button_to_return_to_discover_page_when_searching.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_header_top_rated_movies_when_selected.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_header_with_the_search_query_if_searching.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_less_than_40_names_and_averages_if_less_than_40_matches.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/displays_no_movies_found_if_search_has_no_returns.yml
  spec/fixtures/vcr_cassettes/User_Movies_results_index_page/as_a_user/viewable_elements/does_not_display_no_movies_found_if_search_returns_movies.yml
Labels: enhancement, API consumption

#34 Resloves #7
  app/controllers/users_controller.rb
  app/poros/movie.rb
  app/views/users/show.html.erb
  spec/features/users/show_spec.rb
  spec/fixtures/vcr_cassettes/Users_show_page/as_a_user/viewable_elements/displays_a_viewing_party_section.yml
Labels: enhancement, API consumption

#36 Resolves #3
  app/poros/movie.rb
  app/views/user_movies/show.html.erb
  spec/features/user_movies/show_spec.rb
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/clickable_elements/redirects_to_create_a_new_viewing_party_for_the_user_movie.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/clickable_elements/returns_back_to_the_discover_page_when_clicked.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_a_button_to_create_a_new_viewing_party_for_user_movie.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_a_button_to_return_to_discover_page.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_all_movie_reviews_on_the_page.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_author_and_content_for_a_review.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_header_of_the_movie_title.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_the_10_cast_members.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_the_count_of_the_reviews_for_the_movie.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_the_movie_genres.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_the_movie_runtime.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_the_movie_summary.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/viewable_elements/displays_the_vote_average.yml
  spec/poros/movie_spec.rb
Labels: enhancement, API consumption

#38 Rubocop
  Gemfile
  Gemfile.lock
  app/controllers/landing_controller.rb
  app/controllers/parties_controller.rb
  app/controllers/user_movies_controller.rb
  app/controllers/user_parties_controller.rb
  app/controllers/users_controller.rb
  app/facades/movie_facade.rb
  app/models/party.rb
  app/models/user.rb
  app/poros/cast.rb
  app/poros/movie.rb
  app/poros/review.rb
  app/services/cast_service.rb
  app/services/movie_service.rb
  app/services/review_service.rb
  db/migrate/20220201043506_create_parties.rb
  db/migrate/20220202181400_create_user_parties.rb
  spec/facades/movie_facade_spec.rb
  spec/features/landing/index_spec.rb
  spec/features/layouts/application_spec.rb
  spec/features/parties/new_spec.rb
  spec/features/user_movies/index_spec.rb
  spec/features/user_movies/show_spec.rb
  spec/features/users/discover_spec.rb
  spec/features/users/new_spec.rb
  spec/features/users/show_spec.rb
  spec/fixtures/vcr_cassettes/MovieService/class_methods/_search_movies/returns_array_of_max_40_movies_if_more_than_40_matches.yml
  spec/fixtures/vcr_cassettes/User_movies_show/detail_page/as_a_user/clickable_elements/redirects_to_create_a_new_viewing_party_for_the_user_movie.yml
  spec/models/party_spec.rb
  spec/models/user_party_spec.rb
  spec/poros/cast_spec.rb
  spec/poros/movie_spec.rb
  spec/poros/review_spec.rb
  spec/rails_helper.rb
  spec/services/cast_service_spec.rb
  spec/services/movie_service_spec.rb
  spec/services/review_service_spec.rb
Labels: enhancement
